In [10]:
DATA = r"C:\Users\KIIT\01_ONGC\Intrusion Detection Datasets\Labelled\binary2_cleaned_combined_file.csv"

In [17]:
import pandas as pd
import numpy as np
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, roc_auc_score, classification_report, matthews_corrcoef, log_loss, confusion_matrix
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
import time
import joblib

In [18]:
# Load the dataset from a CSV file and split into train and test sets
def load_and_split_dataset(file_path, test_size=0.2, random_state=42):
    df = pd.read_csv(file_path)
    X = df.drop('Label', axis=1).values
    y = df['Label'].values
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=test_size, random_state=random_state)
    return X_train, X_test, y_train, y_test

# Specify the path to the dataset CSV file
dataset_path = DATA

# Load and split the dataset
X_train, X_test, y_train, y_test = load_and_split_dataset(dataset_path)

# Handle infinite and large values
X_train[np.isinf(X_train)] = np.finfo('float64').max  # Replace infinite values with a large finite value
X_test[np.isinf(X_test)] = np.finfo('float64').max  # Replace infinite values with a large finite value

# Handle missing values
imputer = SimpleImputer(strategy='mean')
X_train = imputer.fit_transform(X_train)
X_test = imputer.transform(X_test)

# Scale the data
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

C:\ProgramData\anaconda3\Lib\site-packages\numpy\core\_methods.py:49: RuntimeWarning: overflow encountered in reduce
  return umr_sum(a, axis, dtype, out, keepdims, initial, where)


### Random Forest

In [19]:
# Define the hyperparameters
n_estimators = 192
max_depth = 6
min_samples_split = 6
random_state = 96

# Create a Random Forest classifier
classifier = RandomForestClassifier(
    n_estimators=n_estimators,
    max_depth=max_depth,
    min_samples_split=min_samples_split,
    random_state=random_state
)

# Train the classifier on the training data
classifier.fit(X_train, y_train)

RandomForestClassifier(max_depth=6, min_samples_split=6, n_estimators=192,
                       random_state=96)

In [20]:
# Make predictions on the testing data
predictions = classifier.predict(X_test)

In [21]:
# Calculate evaluation metrics
auc = roc_auc_score(y_test, predictions)
classification = classification_report(y_test, predictions)
accuracy = accuracy_score(y_test, predictions)
mcc = matthews_corrcoef(y_test, predictions)
logloss = log_loss(y_test, classifier.predict_proba(X_test))

# Print the evaluation metrics
print("AUC: {:.4f}".format(auc))
print("Classification Report:\n", classification)
print("Accuracy: {:.4f}".format(accuracy))
print("MCC: {:.4f}".format(mcc))
print("Log Loss: {:.4f}".format(logloss))

from sklearn.metrics import confusion_matrix
# Calculate the confusion matrix
conf_matrix = confusion_matrix(y_test, predictions)

# Print the confusion matrix
print("Confusion Matrix:")
print(conf_matrix)

# import joblib

# # Save the trained classifier model to a file
# model_filename = r"C:\Users\KIIT\Desktop\SEM-VII\Major Project\CICIDS\RF.pkl"
# joblib.dump(classifier, model_filename)

AUC: 0.9510
Classification Report:
               precision    recall  f1-score   support

           0       1.00      0.90      0.95      5257
           1       0.97      1.00      0.99     18730

    accuracy                           0.98     23987
   macro avg       0.99      0.95      0.97     23987
weighted avg       0.98      0.98      0.98     23987

Accuracy: 0.9781
MCC: 0.9356
Log Loss: 0.0637
Confusion Matrix:
[[ 4746   511]
 [   14 18716]]


### Gradient Boosting Classifier

In [22]:
## STEP 4
# Create a Gradient Boosting classifier
classifier = GradientBoostingClassifier()

# Train the classifier on the training data
classifier.fit(X_train, y_train)

GradientBoostingClassifier()

In [23]:
## STEP 5
# Make predictions on the testing data
predictions = classifier.predict(X_test)

In [24]:
# Calculate evaluation metrics
auc = roc_auc_score(y_test, predictions)
classification = classification_report(y_test, predictions)
accuracy = accuracy_score(y_test, predictions)
mcc = matthews_corrcoef(y_test, predictions)
logloss = log_loss(y_test, classifier.predict_proba(X_test))

# Print the evaluation metrics
print("AUC: {:.4f}".format(auc))
print("Classification Report:\n", classification)
print("Accuracy: {:.4f}".format(accuracy))
print("MCC: {:.4f}".format(mcc))
print("Log Loss: {:.4f}".format(logloss))

from sklearn.metrics import confusion_matrix
# Calculate the confusion matrix
conf_matrix = confusion_matrix(y_test, predictions)

# Print the confusion matrix
print("Confusion Matrix:")
print(conf_matrix)

# import joblib

# # Save the trained classifier model to a file
# model_filename = r"C:\Users\KIIT\Desktop\SEM-VII\Major Project\CICIDS\RF.pkl"
# joblib.dump(classifier, model_filename)

AUC: 0.9961
Classification Report:
               precision    recall  f1-score   support

           0       1.00      0.99      0.99      5257
           1       1.00      1.00      1.00     18730

    accuracy                           1.00     23987
   macro avg       1.00      1.00      1.00     23987
weighted avg       1.00      1.00      1.00     23987

Accuracy: 0.9976
MCC: 0.9929
Log Loss: 0.0138
Confusion Matrix:
[[ 5222    35]
 [   23 18707]]


### Decision Tree

In [26]:
from sklearn.tree import DecisionTreeClassifier
# Create a Decision Tree classifier
classifier = DecisionTreeClassifier()

# Train the classifier on the training data
classifier.fit(X_train, y_train)

# Make predictions on the testing data
predictions = classifier.predict(X_test)

In [27]:
# Calculate evaluation metrics
auc = roc_auc_score(y_test, predictions)
classification = classification_report(y_test, predictions)
accuracy = accuracy_score(y_test, predictions)
mcc = matthews_corrcoef(y_test, predictions)
logloss = log_loss(y_test, classifier.predict_proba(X_test))

# Print the evaluation metrics
print("AUC: {:.4f}".format(auc))
print("Classification Report:\n", classification)
print("Accuracy: {:.4f}".format(accuracy))
print("MCC: {:.4f}".format(mcc))
print("Log Loss: {:.4f}".format(logloss))

from sklearn.metrics import confusion_matrix
# Calculate the confusion matrix
conf_matrix = confusion_matrix(y_test, predictions)

# Print the confusion matrix
print("Confusion Matrix:")
print(conf_matrix)

# import joblib

# # Save the trained classifier model to a file
# model_filename = r"C:\Users\KIIT\Desktop\SEM-VII\Major Project\CICIDS\RF.pkl"
# joblib.dump(classifier, model_filename)

AUC: 0.9994
Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00      5257
           1       1.00      1.00      1.00     18730

    accuracy                           1.00     23987
   macro avg       1.00      1.00      1.00     23987
weighted avg       1.00      1.00      1.00     23987

Accuracy: 0.9995
MCC: 0.9987
Log Loss: 0.0165
Confusion Matrix:
[[ 5252     5]
 [    6 18724]]


In [30]:
### Extremely Randomized Tree

In [29]:
from sklearn.ensemble import ExtraTreesClassifier
# Create an Extra Trees classifier
classifier = ExtraTreesClassifier()

# Train the classifier on the training data
classifier.fit(X_train, y_train)

# Make predictions on the testing data
predictions = classifier.predict(X_test)


In [31]:
# Calculate evaluation metrics
auc = roc_auc_score(y_test, predictions)
classification = classification_report(y_test, predictions)
accuracy = accuracy_score(y_test, predictions)
mcc = matthews_corrcoef(y_test, predictions)
logloss = log_loss(y_test, classifier.predict_proba(X_test))

# Print the evaluation metrics
print("AUC: {:.4f}".format(auc))
print("Classification Report:\n", classification)
print("Accuracy: {:.4f}".format(accuracy))
print("MCC: {:.4f}".format(mcc))
print("Log Loss: {:.4f}".format(logloss))

from sklearn.metrics import confusion_matrix
# Calculate the confusion matrix
conf_matrix = confusion_matrix(y_test, predictions)

# Print the confusion matrix
print("Confusion Matrix:")
print(conf_matrix)

# import joblib

# # Save the trained classifier model to a file
# model_filename = r"C:\Users\KIIT\Desktop\SEM-VII\Major Project\CICIDS\RF.pkl"
# joblib.dump(classifier, model_filename)

AUC: 0.9991
Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00      5257
           1       1.00      1.00      1.00     18730

    accuracy                           1.00     23987
   macro avg       1.00      1.00      1.00     23987
weighted avg       1.00      1.00      1.00     23987

Accuracy: 0.9993
MCC: 0.9979
Log Loss: 0.0025
Confusion Matrix:
[[ 5250     7]
 [   10 18720]]


In [34]:
### AdaBoost

In [32]:
from sklearn.ensemble import AdaBoostClassifier
# Create an AdaBoost classifier
classifier = AdaBoostClassifier()

# Train the classifier on the training data
classifier.fit(X_train, y_train)

# Make predictions on the testing data
predictions = classifier.predict(X_test)

In [33]:
# Calculate evaluation metrics
auc = roc_auc_score(y_test, predictions)
classification = classification_report(y_test, predictions)
accuracy = accuracy_score(y_test, predictions)
mcc = matthews_corrcoef(y_test, predictions)
logloss = log_loss(y_test, classifier.predict_proba(X_test))

# Print the evaluation metrics
print("AUC: {:.4f}".format(auc))
print("Classification Report:\n", classification)
print("Accuracy: {:.4f}".format(accuracy))
print("MCC: {:.4f}".format(mcc))
print("Log Loss: {:.4f}".format(logloss))

from sklearn.metrics import confusion_matrix
# Calculate the confusion matrix
conf_matrix = confusion_matrix(y_test, predictions)

# Print the confusion matrix
print("Confusion Matrix:")
print(conf_matrix)

# import joblib

# # Save the trained classifier model to a file
# model_filename = r"C:\Users\KIIT\Desktop\SEM-VII\Major Project\CICIDS\RF.pkl"
# joblib.dump(classifier, model_filename)

AUC: 0.9902
Classification Report:
               precision    recall  f1-score   support

           0       0.99      0.98      0.99      5257
           1       1.00      1.00      1.00     18730

    accuracy                           0.99     23987
   macro avg       0.99      0.99      0.99     23987
weighted avg       0.99      0.99      0.99     23987

Accuracy: 0.9936
MCC: 0.9813
Log Loss: 0.6006
Confusion Matrix:
[[ 5173    84]
 [   69 18661]]


### Neural Network

In [35]:
from keras.models import Sequential
from keras.layers import Dense

# Create a neural network classifier
model = Sequential()
model.add(Dense(128, activation='relu', input_dim=X_train.shape[1]))
model.add(Dense(64, activation='relu'))
model.add(Dense(1, activation='sigmoid'))

# Compile the model
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])


# Train the classifier on the training data
model.fit(X_train, y_train, epochs=10, batch_size=32, verbose=1)

# Make predictions on the testing data
predictions = (model.predict(X_test) > 0.5).astype(int).flatten()




Epoch 1/10


2999/2999 [==============================] - 13s 3ms/step - loss: 0.0482 - accuracy: 0.9855
Epoch 2/10
2999/2999 [==============================] - 8s 3ms/step - loss: 0.0249 - accuracy: 0.9929
Epoch 3/10
2999/2999 [==============================] - 10s 3ms/step - loss: 0.0198 - accuracy: 0.9943
Epoch 4/10
2999/2999 [==============================] - 9s 3ms/step - loss: 0.0176 - accuracy: 0.9951
Epoch 5/10
2999/2999 [==============================] - 9s 3ms/step - loss: 0.0171 - accuracy: 0.9956
Epoch 6/10
2999/2999 [==============================] - 9s 3ms/step - loss: 0.0152 - accuracy: 0.9958
Epoch 7/10
2999/2999 [==============================] - 12s 4ms/step - loss: 0.0150 - accuracy: 0.9957
Epoch 8/10
2999/2999 [==============================] - 9s 3ms/step - loss: 0.0151 - accuracy: 0.9959
Epoch 9/10
2999/2999 [==============================] - 8s 3ms/step - loss: 0.0133 - accuracy: 0.9961
Epoch 10/10
750/750 [==============================] - 2s 2ms/step


In [36]:
# Calculate evaluation metrics
auc = roc_auc_score(y_test, predictions)
classification = classification_report(y_test, predictions)
accuracy = accuracy_score(y_test, predictions)
mcc = matthews_corrcoef(y_test, predictions)
logloss = log_loss(y_test, model.predict(X_test))

# Print the evaluation metrics
print("AUC: {:.4f}".format(auc))
print("Classification Report:\n", classification)
print("Accuracy: {:.4f}".format(accuracy))
print("MCC: {:.4f}".format(mcc))
print("Log Loss: {:.4f}".format(logloss))

from sklearn.metrics import confusion_matrix
# Calculate the confusion matrix
conf_matrix = confusion_matrix(y_test, predictions)

# Print the confusion matrix
print("Confusion Matrix:")
print(conf_matrix)

# import joblib

# # Save the trained classifier model to a file
# model_filename = r"C:\Users\KIIT\Desktop\SEM-VII\Major Project\CICIDS\NN.pkl"
# joblib.dump(classifier, model_filename)

750/750 [==============================] - 1s 1ms/step
AUC: 0.9945
Classification Report:
               precision    recall  f1-score   support

           0       0.99      0.99      0.99      5257
           1       1.00      1.00      1.00     18730

    accuracy                           1.00     23987
   macro avg       0.99      0.99      0.99     23987
weighted avg       1.00      1.00      1.00     23987

Accuracy: 0.9964
MCC: 0.9894
Log Loss: 0.0127
Confusion Matrix:
[[ 5210    47]
 [   40 18690]]
